spring.jpa.hibernate.ddl-auto: create
spring.datasource.url: "jdbc:mysql://localhost:3306/Chat?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
spring.datasource.username: root
spring.datasource.password: 03896njhn03896
spring.freemarker.expose-request-attributes: true